import type { Metadata } from "next";
import { Roboto, Arvo } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Shared/Navbar/Navbar";
import Footer from "@/Components/Shared/Footer/Footer";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Testify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-black text-white ${roboto.className}`}>
        <Navbar />
        <div className="0 container mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
